function h = plot_points(P,opts)

    d = size(P,2);
    assert( d==2 || d==3 );

    if nargin < 2
        opts = struct; 
    end
    
    % Coords
    X = P(:,1);
    Y = P(:,2);
    if d==2
        Z = zeros(size(X));
    else
        Z = P(:,3);
    end
    
    % Scale    
    if isfield(opts,'Scale')
        S = opts.Scale;
    elseif isfield(opts,'MarkerSize')
        S = opts.MarkerSize*10;
    else
        S = 100;
    end
    
    % Color
    if isfield(opts,'Color')
        C = opts.Color;
    elseif ~isfield(opts,'Color') && ...
        isfield(opts,'ColorMap') && ...
        isfield(opts,'ColorIndex')
        %disp('plot_points with cmap');
        C = opts.ColorMap(mod(opts.ColorIndex-1,size(opts.ColorMap,1))+1,:); 
    else
        C = 'k';
    end
    
    % Plot
    h = scatter3(X,Y,Z,S,C,'filled');
    
%     if d==2
%         h = plot(...
%             X(:,1),...
%             X(:,2),...
%             'LineStyle', 'none', ...
%             'Marker',    options.Marker, ...
%             'MarkerSize',options.MarkerSize, ...
%             'Color',     options.Color,...
%             'LineWidth', 2 ...
%             );
%         if options.ShowLabels
%             hText = text(...
%                 X(:,1)',...
%                 X(:,2)',...
%                 strsplit(num2str(0:size(X,1)-1)),...
%                 'FontSize',options.FontSize);
%         end
%     else
%         h = plot3(...
%             X(:,1),...
%             X(:,2),...
%             X(:,3),...
%             'LineStyle', 'none', ...
%             'Marker',    options.Marker, ...
%             'MarkerSize',options.MarkerSize, ...
%             'Color',     options.Color,...
%             'LineWidth', 2 ...
%             );
%         if options.ShowLabels
%             hText = text(...
%                 X(:,1)',...
%                 X(:,2)',...
%                 X(:,3)',...
%                 strsplit(num2str(0:size(X,1)-1)),...
%                 'FontSize',options.FontSize);
%         end
%     end
end